version: "3.2"
services:
  proxy:
    image: "nginx:1.23.3-alpine"
    ports:
      - "${PROJET_PROXY_HTTP_PORT}:80"
    networks:
      - project
    volumes:
      - type: bind
        source: ./teacher/config/nginx/nginx.conf
        target: /etc/nginx/conf.d/default.conf
      - type: bind
        source: ./teacher/login-form
        target: /usr/share/nginx/html
    depends_on:
      - front
      - swagger
      - auth
      - back
  front:
    image: "node:18.12.1-alpine3.17"
    networks:
      - project
    volumes:
      - type: bind
        source: "./packages/react-component"
        target: "/app"
    command: /app/run.sh
    working_dir: /app
    environment:
      SUBJECT: "${SUBJECT}"
      WATCH_MOD: "${WATCH_MOD}"
      PROJET_PROXY_HTTP_PORT: "${PROJET_PROXY_HTTP_PORT}"
    dns:
      - 8.8.8.8
  back:
    build: 
      dockerfile: Dockerfile
      context: teacher/docker/back/
    networks:
      - project
    volumes:
      - type: bind
        source: "./packages/express-middleware"
        target: "/app"
      - type: bind
        source: "./subjects/${SUBJECT}/chai"
        target: "/test"
      - type: bind
        source: "./teacher/docker/back/test.sh"
        target: "/test.sh"
      - type: bind
        source: "./subjects/${SUBJECT}/sql"
        target: "/sql"
      - type: bind
        source: "./share"
        target: "/share"
    command: /app/run.sh
    working_dir: /app
    environment:
      BACKEND_PORT: 8080
      SUBJECT: "${SUBJECT}"
      DB_PATH: "/share/db.db"
      WATCH_MOD: "${WATCH_MOD}"
      JWT_SECRET: "qwertyuiopasdfghjklzxcvbnm123456"
    dns:
      - 8.8.8.8
  swagger:
    image: swaggerapi/swagger-ui:v3.37.2
    networks:
      - project
    volumes:
      - type: bind
        source: "./subjects/${SUBJECT}/swagger"
        target: /swagger_spec
    environment:
      - SWAGGER_JSON=/swagger_spec/swagger.yml
      - PORT=80
  auth:
    build: 
      dockerfile: Dockerfile
      context: teacher/auth/back
    networks:
      - project
    volumes:
      - type: bind
        source: "./share"
        target: "/share"
    environment:
      JWT_SECRET: "qwertyuiopasdfghjklzxcvbnm123456"
      DB_PATH: "/share/db.db"
    depends_on:
      - back
networks:
  project:
    driver: bridge