- name: Push docker secret
  block:
    - name: "push secret in docker secret {{ _docker_secret_name }}" 
      docker_secret:
        name: "{{ _docker_secret_name }}"
        data: "{{ _docker_secret_data }}"
      register: _docker_secret_os_designate_traefik
      become: yes
  rescue:
    - name: "Remove docker secret {{ _docker_secret_name }} in {{ _docker_service_name }}"
      command: 
        cmd: "docker service update --secret-rm {{ _docker_secret_name }} {{ _docker_service_name }}"
      become: yes
    - name: "Push secret in docker secret {{ _docker_secret_name }}" 
      docker_secret:
        name: "{{ _docker_secret_name }}"
        data: "{{ _docker_secret_data }}"
      become: yes